name: Auto Bus Crawler

on:
  schedule:
    # Chạy tự động mỗi 30 phút, từ 23h đêm đến 13h chiều (UTC), tức 6h sáng đến 20h tối (Việt Nam)
    - cron: '*/30 23,0-13 * * *'  
  # Cho phép bấm nút chạy bằng tay trên web GitHub (rất tiện để test)
  workflow_dispatch: 

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        # Bổ sung h2 (HTTP/2 lách tường lửa), tqdm (log), và httpx-socks (hỗ trợ proxy)
        run: |
          python -m pip install --upgrade pip
          pip install httpx httpx-socks h2 pymongo certifi python-dotenv pydantic-settings tqdm

      - name: Run Crawler
        env:
          # 1. Kéo SECRETS (Dữ liệu bảo mật, mật khẩu)
          MONGO_URI: ${{ secrets.MONGO_URI }}
          VN_PROXY: ${{ secrets.VN_PROXY }}
          
          # 2. Kéo VARIABLES (Cấu hình không bảo mật mà bạn vừa tạo)
          MONGO_DB_NAME: ${{ vars.MONGO_DB_NAME }}
          MONGO_COLLECTION_BUS_SPEEDS: ${{ vars.MONGO_COLLECTION_BUS_SPEEDS }}
          
          # 3. Môi trường cứng (Hardcoded envs)
          TELEGRAM_BOT_TOKEN: "dummy_token"
          BUS_API_BASE_URL: "https://apicms.ebms.vn"
          
          # Báo cho Python biết thư mục gốc ở đâu để lệnh "from app.core..." không bị lỗi
          PYTHONPATH: . 
        
        # Chạy file crawler theo đúng đường dẫn thư mục của bạn
        run: python crawler/github_crawler.py
